### PR TITLE
Daily2 Data Entry Form

### LINKED ISSUE #496: form_Daily2 - Data Entry Form For Daily Data For The Whole Month
Also mentioned in #574

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #496
Also mentioned in #574

This PR Addresses the issues mentioned by @smachua and @mhabimana 

> • Missing Text Box for – “Assign same value to all obs”,
> • Add New not sequencing to the next new record and Flags not clearing,
> • Error on uploading – (DBNull to type string invalid).

### CODE REVIEW

**Comment by Patowhiz** [comment]
@smachua @mhabimana  I removed the textbox because of what was discussed in the workshop in regards to simplifying the forms and minimising the number of controls on the form. So when a user click on the button assign same value, an input message box will appear prompting the user to enter the value, afterwhich the value will be set.

same value

I can revert this back to it's previous implementation if the users won't find this easy to use.

**Comment by Patowhiz** [comment]
@mhabimana  The upload form will not only show the progress but also the record that were not uploaded because of errors

upload

**Comment by mhabimana** [comment]
@Patowhiz : Great,noted. I am yet to test this,will give you my feedback soon

**Comment by mhabimana** [comment]
@Patowhiz - I find it working well now but still the former layout  of the daily form is good compared to the new since it's allow users to move faster. I would suggest we remain with the former form Daily2 layout whereby the default value text box is on the same dialog.
The ability to select the range of data records to upload into the observationinitial is also needed on this dialog since the uploading process is very slow and users don't need to upload all the data from the form to observationinitial each time including what is already existing in the observationinitial . Users need a room to select from the dialog,the list of stations,elements and time period range of  data to upload as an option, uplaod all data in the form can also be there as an option see the example of dialog which can be used here #556

**Comment by Patowhiz** [comment]
On the issue of upload performance, it's worth noting that, the performance appears to be slower than the old form but this is because in the old forms the code was just ignoring all the errors. It was not checking whether records exist or not, and whether it needs to update or insert a new record. In the new form, we've implemented this in a way that aims to achieve data integrity at a cost of performance. So the code is consistently checking for errors and is also determining whether to do an update to the `observationinitial ` table or to insert a new record. So this means separate calls to the database are being called, immensely affecting performance.

I agree with the addition of the dialog. This will help in reducing the number of record that would be checked in the new implementation.

**Comment by Patowhiz** [comment]
@mhabimana I also need to know what is the default sorting column of the records in this form. Is it the `entryDatetime `column?

**Comment by mhabimana** [comment]
@Patowhiz - Thanks,@smachua can you answer this above re-default sorting column?

**Comment by Patowhiz** [comment]
@mhabimana in my last commit I have fixed the issue of same value. Let me know if you are now okay with the current design. To get the changes you will have to update your repository with my code. 
I would have put units into one control but currently we don't have a table for units that links it to the respective elements. This could possibly be a version 5 feature?


units

**Comment by mhabimana** [comment]
@Patowhiz - Thanks for applying necessary correction to the design of this form, however, **AddNew** Button is clearing **units** as well which should not be the case, default units should be fixed in the form unless user decide to change these

**Comment by Patowhiz** [comment]
And what would be the default units? I thought that is dependent on the element selected

**Comment by mhabimana** [comment]
@Patowhiz - Thanks,Below is the screenshot of the daily data entry form with the default values of units. These values should stick to this dialog when the **AddNew** button or any other button is pressed which is not the case now,what is happening is that when the AddNew button is pressed,the units are cleared and units text boxes becomes empty. Please check.
image

**Comment by Patowhiz** [comment]
Yes I'm aware of the clearing, it was intentional, I will change the implementation

**Comment by Patowhiz** [comment]
I will have it show the units on add new

**Comment by mhabimana** [comment]
@Patowhiz - Great,well noted.

**Comment by Steve-Palmer** [comment]
Just picking up on the question about units. I think the current practice is to store everything in the appropriate SI units, so a table of units is not essential - @smachua can confirm. This means that there is less chance for error when the data is retrieved. For the last 50+ years, the instruments and records use SI units, though for very old data, it would be appropriate to do data entry in the units as recorded and convert on storage (and record in the QC codes that conversion had been applied). Particular old units are inches for rainfall and inches or centimetres of Mercury for pressure and Degrees Fahrenheit for temperature. Conversion may be applied for end-user products - DegF are still widely used by non-professionals in the USA, so some American software packages may need DegF. Some of the SI units have changed name over time, e.g. MilliBars to HectoPascal and this is sometimes linked to detailed changes in the fundamental definitions, but the changes are insignificant for meteorology.

**Comment by mhabimana** [comment]
@Steve-Palmer - Thanks you for elaborating on this.You mentioned a point on **conversion at storage**,which I think is not yet in place now in Climsoft. It is possible to switch units of preference before data entry but the next stage is the storage and use of such data before conversion in SI units. I think during the Kitale workshop we have agreed on the possibility to implement the conversion process during the data entry process or when the save button is clicked in case data records are in different units other than SI, what about importing such data into climsoft,is conversion need to be done first before the import process or the system should be able to check and convert such data into SI units? . We have not yet encountered such data but it might be possible in some place and we need to see how we can deal with such data.

**Comment by smachua** [comment]
The best point for converting those data that are not in SI units is while uploading them from Key Entry forms because that's where unit types are are listed. As Steve suggested the converted values may be flagged accordingly. So far no flag has been defined for that purpose. I suggest use of G (for Generated) since it's already there. May be @Patowhiz can try including conversion process in the upload operation that he has been working on.

**Comment by Steve-Palmer** [comment]
I agree with @smachua that at present the data entry form upload process is the appropriate place for unit conversion. However, we will need to revisit this, probably in Climsoft V6 or OpenCDMS when we implement full QC history. At that stage, we would probably need to record the original keyed value and units in the QC history, then do the conversion for the "latest QC'd" value. When we get the code for the Data Rescue modules from ACMAD, we should check how (or if) that handles the problem.

**Comment by mhabimana** [comment]
Sounds great

**Pull request merged**
