### PR TITLE
Creates the hourly2 and updates hourly data entry form to use 2 sequencers; seq_element and sequencing by date

### LINKED ISSUE #741: Hourly data entry form to have 2 sequencing option
Recently, a user asked for the hourly data entry to sequence either by seq_element or seq_daily_element.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #741.

@mhabimana and @smachua this is now ready for review.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@mhabimana @smachua 

To test the hourly2 data entry form in this PR you will have to:
1. Add the hourly2 record in the `data_forms` table., as shown in the screenshot below. This will make accessible for selection in the forms selection dialog. 


2. Then execute the sql script for creating the table for storing hourly2 data. Attached is a zip file that contains the file with sql script for creating the `form_hourly2` table. You will need to run it for testing.
[frm_hourly2_table.zip](https://github.com/climsoft/Climsoft/files/14662780/frm_hourly2_table.zip).

Note we still have to expose the `seq_hour` table in the front end, to allow users customise the sequence of the hour.

To test the hourly data entry form in regards to changing the sequencer between element and day, first add the setting in the `regKeys` table. Then you will be able to access the setting in the **General Settings** dialog. The value can be element or day.
Note I used **key15**.

**Comment by Patowhiz** [comment]
@mhabimana this is now ready for you to test.
1. Hourly data entry form.
2. Hourly2 entry form.

Note, @smachua will do the uploading. I did manage to add the bits to support it but there an error related to the temporary created file accessibility.

**Comment by Patowhiz** [comment]
@mhabimana I have explained in this [comment](https://github.com/climsoft/Climsoft/pull/742#issuecomment-2008831631) how to test the hourly data entry form. The implementation is based on your idea of the administrator being able to change which sequencer to be used. The sequencer setting will be done in the General Settings dialog. Like mentioned in the comment, the values will be either **element** or **day**. I have added this as **key20**.

**Review by mhabimana — APPROVED** [review]
Reviewed and approved for merging with the master.

**Pull request merged**
