### PR TITLE
Adds translations of new labels

### PR DESCRIPTION
**Pull request by Patowhiz**
@mhabimana @smachua this is now ready for review.

### CODE REVIEW

**Review by mhabimana — CHANGES_REQUESTED** [review]
Few issues need to be looked at :
1. Data selection for monthly data dialog (transpose and numbers of missing days allowed to compute monthly total  options are missing)
2. Metadata- import-Update has a bug that requires a fix(return a clear message under message box if there is a problem)
3. Adjustment  of Metadata Import dialog command buttons is required.

**Comment by smachua** [comment]
@Patowhiz I am going to look at the points you have listed the respond soon.

**Comment by Patowhiz** [comment]
@mhabimana I have addressed item 1 & 3 and also added translations from CrowdIn. This is now ready for your review.

@smachua I think item 2 relates to having more descriptive error message. @mhabimana are you happy if the bug fix and error message is done in a separate PR?

**Review by mhabimana — APPROVED** [review]
Reviewed and approved.

**Pull request merged**
