### PR TITLE
Climat msg update

### PR DESCRIPTION
**Pull request by smachua**

### CODE REVIEW

**Comment by mhabimana** [comment]
@smachua: Expand a bit this command button to fit French and Portuguese. Change as well the vesion to V4.2.2.
image

**Comment by smachua** [comment]
@mhabimana it's better you first merge the #746 then I work on the other issues.

**Comment by mhabimana** [comment]
@smachua 👍

**Review by mhabimana — APPROVED** [review]
Reviewed and approved.

**Pull request merged**
