### PR TITLE
Added approved French translations and refactored dialogs to work with the translations, added R-Instat output.

### LINKED ISSUE #687: Import files dialog - Texts, CLICOM, AWS, NOAA GTS, Dekadal
The selection of the file type is currently hard coded into the title and label control of the import dialog. However this are currently translated string literals. 
As discussed, the dialogs involved need to be refactored to not use these translated string literals

### LINKED ISSUE #688: Form products selection
The selection of the products is currently hard coded into controls and string literals that are translated during runtime.
As discussed, the dialogs involved need to be refactored to not use these translated string literals

### LINKED ISSUE #689: Data entry forms activation and selection
The selection and activation of the data entry forms is currently hard coded into controls and string literals that are translated during runtime.
As discussed, the dialogs involved need to be refactored to not use these translated string literals

### LINKED ISSUE #690: French translations
The current French translations are just auto translations from C.rowdIn
The approved French translations done by @mhabimana need to be added into the translations database.
Dialogs also need to be refactored to work well with the new French translations

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #690 
Fixes #689 
Fixes #688 
Fixes #687 

@mhabimana @smachua this is ready for your review.
I'm also happy to discuss with both of you about the changes made. Thanks.

### CODE REVIEW

**Comment by smachua** [comment]
@mhabimana we may need to discuss when those adjustments can be concluded. There are some urgent requests from users that require changes on the same forms and implementing them may cause serious conflicts

**Comment by Patowhiz** [comment]
@mhabimana I have now fixed the bug that was in the products selection. Kindly test.
Thanks.

**Comment by mhabimana** [comment]
@Patowhiz -Thanks,will do. As agreed,can you also remove the link on the "language" and  put this on the "change language" ?
image

**Comment by mhabimana** [comment]
@Patowhiz - Good if you can leave this table blank by default to give users the liberty to select a desired products among the dropdown list of products category. By default  you are displaying the data (données) but would be good to display a blank,then users can select a specific product category from the list:
1.Desired(OK)
image

2. Not desired(Not OK)
image

**Comment by Patowhiz** [comment]
@mhabimana I have fixed the 2 forms above. Kindly test.
Thanks.

**Comment by Patowhiz** [comment]
@mhabimana I have now added all @smachua changes into this PR. You can now test.
@mhabimana @smachua also test the changes from @smachua.
Thanks

**Comment by mhabimana** [comment]
@Patowhiz - Great,let me have a look

**Comment by mhabimana** [comment]
@Patowhiz - I am not seeing the latest changes on data entry forms added by @smachua (e.g.: the **Push** feature) I wonder if the merging was done properly.

**Comment by Patowhiz** [comment]
It's there. Counter check the branch and pr you are reviewing. 
I haven't merged.

**Pull request merged**
