### PR TITLE
ucrHourly Data Entry Form

### LINKED ISSUE #585: Hourly Data Form Entry
This issue relates to issue #574
Based on @smachua observations

> • On key entry, text box for Hour 19 is skips on both Enter and Tab keys. The same text box
> also not working as expected on Delete and Insert Cell actions,
> •No action on Upload button.

These bugs need to be fixed.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #585
Also mention in #574
@smachua @mhabimana this is ready for review.

This PR is addressing hourly data form.
Test the sequencer(add new),  the upload, the performance generally, the flags etc
Please thoroughly check the form because the principled used on this form are similar to the other data entry forms. 
It will help me alot in implementing the other data entry forms.
I'm happy to include any additions that were not included previously on this form.

### CODE REVIEW

**Comment by Patowhiz** [comment]
@smachua @mhabimana should the records loaded in the data entry forms be ordered by entry date?

**Comment by Patowhiz** [comment]
I have set the default ordering to use column entryDatetime

**Comment by mhabimana** [comment]
@Patowhiz - I can see,issues raised were addressed in this PR but process of uploading many records (e.g. 20.000 ) is very slow. What about adding the feature raised under issue #556. I think this may help address  this issue of speed during the upload time.The idea here is to enable the system to upload a selected period of data from the data entry form into observationinitial instead of upload everything each and every time including what is already existing in observationinitial.

**Comment by Patowhiz** [comment]
Thanks for your feedback @mhabimana . I was going to do issue #556 in a separate PR. So I think we can have this merged once it is ready. And then I will implement the new way of uploading the records using the dialog mention in issue #556. 

In the meantime, I think it will help if you test this PR for also all the other issues not mentioned. To just make sure we don't have bugs that we could easily pick out.

**Comment by mhabimana** [comment]
@Patowhiz 👍 well noted.

**Pull request merged**
